### ISSUE TITLE
Block Table: Incorrect <thead> Markup

### ISSUE THREAD

**Issue by sagarjadhav** [Travelopia/wordpress-blocks#22]
The current <thead> markup is incorrect and should be fixed. The problematic code is as follows:

```
<thead>
  <tr>
    <td>T Header</td>
    <td>T Header</td>
  </tr>
</thead>
```

The correct <thead> markup should be:

```
<thead>
  <tr>
    <th>T Header</th>
    <th>T Header</th>
  </tr>
</thead>
```

**Comment by junaidbhura** [comment]
@abhi3315 Would you be able to take a look at this one?

@sagarjadhav In the meantime, please add styles for both in the website's CSS, so when this is updated - it will work too

**Comment by abhi3315** [comment]
@junaidbhura I have raised the PR. Please take a look.
https://github.com/Travelopia/wordpress-blocks/pull/23

**Comment by junaidbhura** [comment]
Thanks @abhi3315 !

@sagarjadhav a new version is released, can you please check if this fixes your issue? https://github.com/Travelopia/wordpress-blocks/releases/tag/1.1.1

**Comment by sagarjadhav** [comment]
@junaidbhura This is working as expected. Thanks

**Comment by junaidbhura** [comment]
Thanks @sagarjadhav
